# application-dev.yml

nacos:
  config:
    endpoint: ${NACOS_ENDPOINT}
    namespace: ${NACOS_NAMESPACE}

spring:
  main:
    web-application-type: none
  application:
    name: med-hub
#  cloud:
#    openfeign:
#      lazy-attributes-resolution: true